### PR TITLE
Bugfix/nullable types

### PR DESCRIPTION
**Pull request by ch4mpy**

### CODE REVIEW

**Comment by cavorite** [comment]
Hi @ch4mpy. Thanks for sending this PR. I saw that you created a fork and you changed the package names. 

Do you prefer to fork the repository and take ownership of the project? 

I can close this project and add a note mentioning that you're maintaining an updated version of the plugin.

**Comment by ch4mpy** [comment]
Ooups, sry for the packages, I forgot to restore it. At some point, I ran into some difficulties to publish on a private Nexus and changed it to sure I was pulling updated plugin...

Actually I'm not much more interested in the project ownership  as you are ;)
I just got things work for my use case and wanted to contribute back as your work saved me a lot of time (thank you by the way)

**Comment by cavorite** [comment]
@ch4mpy: No problem at all. Feel free to update the package names and I'll merge this PR. Otherwise, I can do it over the weekend.

**Comment by ch4mpy** [comment]
@cavorite: Hello, I believe I restored your group-id / package names. Ping me if if you need further changes.

**Pull request merged**
